version: 2
jobs:
  build:
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: setup
          command: apk add --no-cache make
      - run:
          name: build
          command: make all
      # - deploy:
      #     name: push
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         login="$(aws ecr get-login)"
      #         ${login}
      #         docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #         docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #       fi

